controller_list:
  - name: fake_ur10e_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_two_finger_gripper_controller
    joints:
      - slide_left
      - slide_right
initial:  # Define initial robot poses.
  - group: ur10e_arm
    pose: home